runtime: python310

entrypoint: gunicorn -b :$PORT app:app

handlers:
  # Serve static files (CSS, JS, images) directly
  - url: /static/(.*)
    static_dir: static/

  # Route everything else to your Flask application
  - url: /.*
    script: auto
